# config_pyiot_ros.yaml 
# IoT Configuration
config_iot:
  mqtt:
    server_url: "broker.mqttdashboard.com"        
    server_port: 1883
    topic_sub: "eyrc/UaHaYix/iot_to_ros"          
    topic_pub: "eyrc/UaHaYix/ros_to_iot"          
    qos: 0
    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"   # ROS nodes can listen to this topic to receive data from MQTT
  google_apps:
    spread_sheet_id: "AKfycbwB7ZAH_QhlbBeYxL4uDePDdWHs6L7-7LZXvP2O83Qc2KuJpcM1tfHVqA"
    web_app_url: "https://script.google.com/macros/s/AKfycbwB7ZAH_QhlbBeYxL4uDePDdWHs6L7-7LZXvP2O83Qc2KuJpcM1tfHVqA/exec"
    submission_sheet_id: "AKfycbw5xylppoda-8HPjt2Tzq4ShU_Xef-Ik-hEtBPcPk0gdGw8095j4RZ7"
    submission_web_app_url: "https://script.google.com/macros/s/AKfycbw5xylppoda-8HPjt2Tzq4ShU_Xef-Ik-hEtBPcPk0gdGw8095j4RZ7/exec"